name: Tests

on:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python v${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install --upgrade pip && pip install pytest
    - name: Test with pytest
      run: poetry run pytest --cov=app __tests__
      env:
        TRANSACT_API_CLIENT_ID: ${{secrets.TRANSACT_API_CLIENT_ID}}
        TRANSACT_API_DEVELOPER_API_KEY: ${{secrets.TRANSACT_API_DEVELOPER_API_KEY}}
